### ISSUE TITLE
Gridlayout, Share options ?

### ISSUE THREAD

**Issue by mkodekar** [whalemare/sheetmenu#1]
Does it support  grid layout for menu items

**Comment by whalemare** [comment]
Now, you can do this with version 1.1
`compile 'com.github.whalemare:sheetmenu:v1.1'`

where you need set GridLayoutManager, you can see this impl [setupGrid()](https://github.com/whalemare/sheetmenu/blob/master/app/src/main/java/ru/whalemare/bottomsheet/MainActivityKotlin.kt)

**Comment by mkodekar** [comment]
thanks buddy you made my day
