### ISSUE TITLE
How do I hide a menu item programmatically?

### ISSUE THREAD

**Issue by tsl-developteam** [whalemare/sheetmenu#12]
How do I hide a menu item programmatically? For example, the menu item for purchasing "No Ads"

**Comment by tsl-developteam** [comment]
@whalemare

**Comment by whalemare** [comment]
If I understand correctly the question, you can pass different params to your menu in different cases. For now, it is possible only by passing different menu files for each case. 
The design of this library was originally aimed at a static `R.menu` files, but not a big problem to alter implementation on dynamic lists. 
At the moment I don't have time to change the library, so I waiting your PR with changes :D
Or wait for changes have been maked by me :) For this, I need month or two

**Comment by tsl-developteam** [comment]
Thank you!

Чт, 16 серп. 2018, 13:03 користувач Anton Vlasov <notifications@github.com>
пише:

**Comment by whalemare** [comment]
Oh, I need 1 year for doing that, so sorry :)
