### ISSUE TITLE
Dismiss sheetmenu when item was clicked

### ISSUE THREAD

**Issue by maddog05** [whalemare/sheetmenu#2]
Maybe and option like
setDismissWhenItemClicked(boolean isDismissAllowed)

**Comment by whalemare** [comment]
Now, you can do it with version 1.2. I am add by default auto-cancel dialog, after click on menu item. You can change this behavior by changing the boolean-balue to **false**
`compile 'com.github.whalemare:sheetmenu:1.2'`

**Comment by maddog05** [comment]
thanks
