### ISSUE TITLE
How can I display the grid menu with the description size below the icon?

### ISSUE THREAD

**Issue by bardoj** [whalemare/sheetmenu#7]
Firstly, thank you for support a good program library.
I made a Grid style 4 * 2 menu with icons and descriptions. However, since one menu size is the same as the icon size, the description can not be displayed on one line.
How can I display the grid menu with the description size below the icon?

Thank you for advance.

![screenshot_20170920-130556](https://user-images.githubusercontent.com/12061972/30626890-ef82557c-9e07-11e7-9844-d59780537552.png)

**Comment by whalemare** [comment]
Thanks for your feedback, @bardoj. 
By [Bottom sheet spec](https://material.io/guidelines/components/bottom-sheets.html#bottom-sheets-specs) from Material Design Components, you should use grid with 3 columns. With a larger number of elements in the row, they will be very closely located to each other, which will adversely affect on UX in your case. 
However, you can make changes that you consider necessary and send me a pull request. In the future I will add automatic calculation of the required number of columns depending on screen and device, but not now.
