### ISSUE TITLE
Create Grid Style

### ISSUE THREAD

**Issue by AliAzaz** [whalemare/sheetmenu#8]
Hi. Your library is too nice.
Can you please tell me how I can create Grid layout menu item?

Thanks

**Comment by whalemare** [comment]
Hello, thanks for your feedback!
You can do this, just applying your custom LayoutManager. In your case it will be `GridLayoutManager`.

You can check [this sample](https://github.com/whalemare/sheetmenu/blob/73b4d303f103fe2e6e26525c7d063684b092be0a/app/src/main/java/ru/whalemare/bottomsheet/MainActivityKotlin.kt#L50) for more details.
I`m answered on your question?
